baseurl = "/"
LanguageCode = "en"
title = "Racktivity"
theme = "landing"
contentdir = "content"
staticdir = "static"
publishdir = "en"
relativeURLs = true
port = 9090

[permalinks]
    post = "/:filename"
    partners = "/:filename"
    customers = "/:filename"
    support = "/:filename"
